language: go

go:
  - tip

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/codegangsta/cli

script: go test github.com/ziagrosvenor/pact-verify-cli/pact-verify && go test github.com/ziagrosvenor/pact-verify-cli/run
